### ISSUE TITLE
Problem: Slider text for Diagonal slider gets behind the images

### ISSUE THREAD

**Issue by peachmorph** [Innvenio/DiagonalSlider#1]
Hi, I am testing your diagonal slider. When I paste the coding into a fixed container and have it positioned in the center of the webpage, the text description label for the images fell behind and got covered up by the sliding images. I have tried changing the z-index number but it does not solve the problem. Can you help to solve this issue?

I can't attached zip files here. If u need to see the codes, I can send it over using private email address.
I will hear from you soon.
Thx u,
Brian

**Comment by aesposito** [comment]
Hi Brian, I need to see the code. Please, send it to dev@innvenio.com. Thanks

**Comment by peachmorph** [comment]
Hi, Aesposito.

I have sent you a private email, with attachment. Kindly review and I shall hear from you soon. Thank you very much.

Regards,
Brian

**Comment by aesposito** [comment]
Comment this code:
$('.content_slider').find('.content_title').css('margin-top',slider.height() - 200);
