### ISSUE TITLE
The most right image "preview" is to small

### ISSUE THREAD

**Issue by Fridleif** [Innvenio/DiagonalSlider#2]
Hello,

is it possible to set the width of the most right image a bit larger? 

Thank you

**Comment by aesposito** [comment]
You can reduce the first slider width.
In this link https://jsfiddle.net/aesposito/5on74dj6/ I put a code that you have to replace for the code in DiagonalSlider.js

In this new code you see a new var called "reduce_first_width" for that you can change the witdh of the first element.

Give it a try!
