### ISSUE TITLE
Resize small to widescreen

### ISSUE THREAD

**Issue by ArianeLux** [Innvenio/DiagonalSlider#3]
Hello Innvenio Team,

Thank you for your awesome work on this library.

I get the following issue when I double-click on top of the browser-window to make it as wide as my screen, there are spaces between the pictures. But after a refresh, everything looks fine.

Can you help me with this?

![homepage](https://cloud.githubusercontent.com/assets/17006827/12719791/8ddef1c2-c8f7-11e5-9466-3b2ae2d63a51.png)

Regards

ArianeLux

**Comment by aesposito** [comment]
Hi, is in this demo http://jsfiddle.net/aesposito/ku3fwu92/ happening the same issue?

**Comment by ArianeLux** [comment]
No, it is not the same issue.

In your demo, there is no diagonal slider anymore. In my demo, there is a diagonal slider, but the pictures are not sticked to their neighbours, there are some spaces between them. This happens after a resize from small screen to widescreen.

**Comment by ArianeLux** [comment]
Hi,

I,finally, found the error. I changed a CSS-Property and it broke everything. I reset the CSS to the standard that you provided and it's all good!!

Sorry!! My mistake!!
